//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Learun.Util.Expression.Operator
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using  Learun.Util.Expression.Operand;

	public class Add : BinaryOperator
	{
        public Add():base("+", PriorityType.AddAndSub)
        {
        }

        public override Operand Evaluate(Operand[] operands)
        {
            base.Evaluate(operands);

            return operands[0] + operands[1];
        }
	}
}

