//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Learun.Util.Expression.Operator
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ShiftLeft : BinaryOperator
	{
        public ShiftLeft()
            : base("<<", PriorityType.MulAndDiv)
        {
        }

        public override Operand.Operand Evaluate(Operand.Operand[] operands)
        {
            base.Evaluate(operands);

            return operands[0] << (int)operands[1].AsFloat;
        }
	}
}

