//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Learun.Util.Expression.Operator
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Or : BinaryOperator
	{
        public Or()
            : base("||", PriorityType.Logic)
        {
        }

        public override Operand.Operand Evaluate(Operand.Operand[] operands)
        {
            base.Evaluate(operands);

            return new Operand.Operand(operands[0].AsBoolean || operands[1].AsBoolean);
        }
	}
}

