//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Learun.Util.Expression.Operator
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class BinaryOperator : Operator
	{
        public BinaryOperator(string token, Operator.PriorityType prio)
            : base(token, prio)
        {
        }

        public override bool IsBinary
        {
            get { return true; }
        }

        public override Operand.Operand Evaluate(Operand.Operand[] operands)
        {
            if (operands.Count() < 2)
                throw new System.NotSupportedException("Binary operator '" + this.TokenName + "' needs two operands.");

            return null;
        }
	}
}

