//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Learun.Util.Expression.Operator
{
	using Learun.Util.Expression.Operand;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Operator : Token
	{
        public enum PriorityType
        {
            Logic = 0,
            Compare = 1,
            Bitwise = 2,
            AddAndSub = 3,
            MulAndDiv = 4,
            Function = 5,
            Unary = 6,
            Parentheses = 7
        };

        private string m_tokenName;
        private PriorityType m_prio;
        
        public Operator(string token, Operator.PriorityType prio)
        {
            m_tokenName = token;
            m_prio = prio;
        }

        public override string TokenName 
        { 
            get { return m_tokenName; } 
        }

        public virtual PriorityType Priority
        {
            get { return m_prio; }
        }

        public override bool IsOperator
        {
            get
            {
                return true;
            }
        }

        public virtual Operand Evaluate(Operand[] operands)
		{
            throw new System.NotImplementedException();
		}

		public virtual int ComparePriority(Operator that)
		{
            if (this.Priority > that.Priority)
                return 1;
            else
                if (this.Priority < that.Priority)
                    return -1;
                else
                    return 0;
		}
	}
}

