//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Learun.Util.Expression.Operator
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Parentheses : Operator
	{
        public Parentheses()
            : base("(", PriorityType.Parentheses)
        {
        }

        public override bool IsParentheses
        {
            get
            {
                return true;
            }
        }
	}
}

