//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Learun.Util.Expression.Operator
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class UnaryOperator : Operator
	{
        public UnaryOperator(string token, Operator.PriorityType prio)
            : base(token, prio)
        {
        }

        public override bool IsUnary
        {
            get
            {
                return true;
            }
        }

        public override Operand.Operand Evaluate(Operand.Operand[] operands)
        {
            if (operands.Count() < 1)
                throw new System.NotSupportedException("Operator '" + this.TokenName + "' needs one operand.");

            return null;
        }
	}
}

