//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Expression.Operand
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class OperandBase
	{
		public virtual float AsFloat
		{
			get;
			private set;
		}

		public virtual bool AsBoolean
		{
			get;
			private set;
		}

		public virtual string AsString
		{
			get;
			private set;
		}

		public virtual bool Validate(int iVal)
		{
			throw new System.NotImplementedException();
		}

		public virtual bool Validate(float fVal)
		{
			throw new System.NotImplementedException();
		}

		public virtual bool Validate(string sVal)
		{
			throw new System.NotImplementedException();
		}

		public virtual bool Validate(OperandBase oVal)
		{
			throw new System.NotImplementedException();
		}

		public virtual string ToString()
		{
			throw new System.NotImplementedException();
		}

		public virtual int CompareTo(OperandBase that)
		{
			throw new System.NotImplementedException();
		}

		public virtual OperandBase From(int iVal)
		{
			throw new System.NotImplementedException();
		}

		public virtual OperandBase From(float fVal)
		{
			throw new System.NotImplementedException();
		}

		public virtual OperandBase From(string sVal)
		{
			throw new System.NotImplementedException();
		}

		public virtual OperandBase From(OperandBase oVal)
		{
			throw new System.NotImplementedException();
		}

	}
}

